# Generated by Django 3.1.3 on 2020-11-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dobrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('elemento', models.SmallIntegerField(choices=[(1, 'AR'), (2, 'ÁGUA'), (3, 'TERRA'), (4, 'FOGO')], verbose_name='Elemento')),
                ('descricao', models.TextField(verbose_name='Descrição Pessoal')),
                ('profissao', models.CharField(max_length=100)),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('genero', models.SmallIntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMININO'), (3, 'NEUTRO')])),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Primeiro acesso')),
            ],
        ),
    ]
