# Generated by Django 3.1.3 on 2020-11-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dobrador',
            name='elemento',
            field=models.CharField(choices=[('AR', 'AR'), ('ÁGUA', 'ÁGUA'), ('TERRA', 'TERRA'), ('FOGO', 'FOGO')], max_length=100, verbose_name='Elemento'),
        ),
        migrations.AlterField(
            model_name='dobrador',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO'), ('NEUTRO', 'NEUTRO')], max_length=100, verbose_name='Gênero'),
        ),
    ]
