# Generated by Django 3.1.3 on 2020-12-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobrador', '0002_auto_20201119_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='dobrador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
